#include<iostream>
using namespace std;

int man(){
    int age=15;
    if(age>=18){
        
    }
    else{
        cout<<"Yoy are not Elagibale for Vote:"<<endl;
    }
     return 0;
}



#include <iostream>
using namespace std;

int main(){
    cout<<"My Name is\n Hariom Shukla\n";
    cout<<"My First Name :"<<endl;
    cout<<"Hariom"<<endl;
    return 0;
}



#include <iostream>
using namespace std;

int main(){
    int age = 25;
    cout<<age<<endl;
    return 0;
}



#include <iostream>
using namespace std;

int main(){
    int age = 25;
    char grade = 'a';
    float pi = 3.14;
    double a = 9.9999999;
    bool issafe = true;
   
   cout<<sizeof(age)<<endl;
   cout<<sizeof(grade)<<endl;
   cout<<sizeof(pi)<<endl;
   cout<<sizeof(a)<<endl;
   cout<<sizeof(issafe)<<endl;
   
    return 0;
}



#include <iostream>
using namespace std;

int main(){
    char grade = 'B';
    int value = grade;
    cout<<value<<endl;
    return 0;
}



#include <iostream>
using namespace std;

int main(){
int age;
cout<<"Enter Your age :"<<endl;
cin>>age;
cout<<"Your Age Is :"<<age<<endl;

return 0;
}



#include <iostream>
using namespace std;

int main(){

    int a=5,b=10;
    cout<<"Addition ofa & b :"<<(a+b)<<endl;//Airthmatic oprator
    cout<<(3<5)<<endl;//relational oprators
    cout<<(3>5)<<endl;

    cout<<!(3>5)<<endl;//Logical oprator

    return 0;
}



#include <iostream>

using namespace std;

int main(){
int a,b;
cout<<"Enter The Value of a"<<endl;

cin>>a;
cout<<"Enter The Value of b"<<endl;
cin>>b;
cout<<"Sum od a & b :"<<(a+b)<<endl;



    return 0;
}



#include <iostream>
using namespace std;

int main(){

    int a =10;
int c = a++;
//int b = ++a;


cout<<c<<endl;


    return 0;
}
